services:
  frontend-map:
    build:
        context: .
        dockerfile: "Frontend/Map/Dockerfile"
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - 3000:3000

  frontend-package-loading:
    build:
      context: .
      dockerfile: "Frontend/PackageLoading/Dockerfile"
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - 3001:3001

  backend:
    build:
        context: ./Backend/
        dockerfile: "/Logistics.Api/Dockerfile"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent http://localhost:80/health || exit 1" ]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 5s
    depends_on:
      redis:
        condition: service_started
      placement:
        condition: service_started
      backend-delivery-planner:
        condition: service_healthy
      backend-data:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "5000:80"
    env_file:
      - .env

  backend-data:
    build:
        context: ./Backend/
        dockerfile: "/Logistics.Database/Dockerfile"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:80/health || exit 1"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 5s
    depends_on:
      redis:
        condition: service_started
      placement:
        condition: service_started
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - 5001:80

  backend-simulation:
    build:
        context: ./Backend/
        dockerfile: "/Logistics.Simulation/Dockerfile"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:80/health || exit 1"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 5s
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - 5003:80

  backend-delivery-planner:
    build:
        context: ./Backend/
        dockerfile: "/Logistics.Deliveries/Dockerfile"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent http://localhost:80/health || exit 1" ]
      interval: 1s
      timeout: 5s
      retries: 20
      start_period: 5s
    env_file:
      - .env
    depends_on:
      redis:
          condition: service_started
      placement:
          condition: service_started
      backend-data:
          condition: service_healthy
      rabbitmq:
          condition: service_healthy
    ports:
      - 5002:80

  backend-dapr:
    build: "Backend/Logistics.Api/dapr/"
    depends_on:
      - backend
    network_mode: "service:backend"

  backend-simulation-dapr:
    build: "Backend/Logistics.Simulation/dapr/"
    depends_on:
      - backend-simulation
    network_mode: "service:backend-simulation"

  backend-data-dapr:
    build: "Backend/Logistics.Database/dapr/"
    depends_on:
      - backend-data
    network_mode: "service:backend-data"

  backend-delivery-planner-dapr:
    build: "Backend/Logistics.Deliveries/dapr/"
    depends_on:
      - backend-delivery-planner
    network_mode: "service:backend-delivery-planner"

  db:
    image: "mysql"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password123 --execute \"SHOW DATABASES;\""
      interval: 1s
      timeout: 3s
      retries: 1000
      start_period: 300s
    env_file:
      - .env
    volumes:
      - ./out/sql:/var/lib/mysql
    ports:
      - "3306:3306"

  zipkin:
    image: "openzipkin/zipkin"
    ports:
      - "9411:9411"

  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"

  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 10s
    environment:
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_USER: admin
    ports:
      - "5672:5672"

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - "./out/seq-data/:/data"