apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: status
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: host
      value: "amqp://admin:password@rabbitmq:5672"
    - name: durable
      value: "true"
    - name: autoAck
      value: "false"
    - name: reconnectWait
      value: "5"
    - name: concurrency
      value: parallel
